name: Build and Test

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    paths:
      - 'kotlin-multiplatform/**'

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Assemble Android Debug
        run: cd kotlin-multiplatform && ./gradlew assembleDebug

      - name: Upload Android Artifacts
        uses: actions/upload-artifact@v5
        with:
          name: android-debug-artifacts
          path: |
            kotlin-multiplatform/**/build/outputs/aar/
            kotlin-multiplatform/**/build/libs/*-android.jar
          retention-days: 30

  build-jvm:
    name: Build JVM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Assemble JVM
        run: cd kotlin-multiplatform && ./gradlew jvmJar

      - name: Upload JVM Artifacts
        uses: actions/upload-artifact@v5
        with:
          name: jvm-artifacts
          path: |
            kotlin-multiplatform/**/build/libs/*-jvm.jar
          retention-days: 30

  build-ios:
    name: Build iOS
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build iOS Debug Frameworks
        run: cd kotlin-multiplatform && ./gradlew linkDebugFrameworkIosArm64 linkDebugFrameworkIosSimulatorArm64 linkDebugFrameworkIosX64

      - name: Upload iOS Artifacts
        uses: actions/upload-artifact@v5
        with:
          name: ios-artifacts
          path: |
            kotlin-multiplatform/**/build/classes/kotlin/iosArm64/main/
            kotlin-multiplatform/**/build/classes/kotlin/iosSimulatorArm64/main/
            kotlin-multiplatform/**/build/classes/kotlin/iosX64/main/
          retention-days: 30

  test-android:
    name: Test Android
    runs-on: ubuntu-latest
    needs: build-android
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Run Android Debug Tests
        run: cd kotlin-multiplatform && ./gradlew testDebugUnitTest

  test-jvm:
    name: Test JVM
    runs-on: ubuntu-latest
    needs: build-jvm
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Run JVM Tests
        run: cd kotlin-multiplatform && ./gradlew jvmTest

  test-ios:
    name: Test iOS
    runs-on: macOS-latest
    needs: build-ios
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Run iOS Tests
        run: cd kotlin-multiplatform && ./gradlew iosSimulatorArm64Test iosX64Test
