name: Build

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    paths:
      - 'kotlin-multiplatform/**'

jobs:
  build:
    name: Kotlin Multiplatform
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Gradle Build
        run: cd kotlin-multiplatform && ./gradlew build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kotlin-multiplatform-build-artifacts
          path: |
            kotlin-multiplatform/compose/build/libs/
            kotlin-multiplatform/compose/build/outputs/
          retention-days: 30
